### ISSUE TITLE
What is "locations" used for?

### ISSUE THREAD

**Issue by cipherchien** [voryx/ThruwayBundle#10]
Dear Sir,

I just try to implement to my project, but I can't figure out what "locations" setting in config.yml is used for.
May I have an example or some tips?  
thanks. 

    locations:
        bundles: ["AppBundle"]
        files:
            - "Acme\\DemoBundle\\Controller\\DemoController"

**Comment by davidwdan** [comment]
This bundle uses annotations to add WAMP actions to methods.  The `locations` config option tells the bundle where to looks for those annotations.  You can either specify a bundle name, in which case, the entire bundle is scanned for those annotations or the name space of individual files.

**Comment by cipherchien** [comment]
Oh~，I got it.  so, If I set up a controller with some annotations, such like: Subscribe. The controller will handle the request from front-end.

thank your reply and your genius works.
