### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by monkey3d** [voryx/ThruwayBundle#12]
Hi,
A small contribution.

use Voryx\ThruwayBundle\Annotation\RPC; cannot be resolved.
---------------------------------------------------------------------------------
/**
  * @Worker("chat", maxProcesses="5")
  */
  class ChatController

need  : use Voryx\ThruwayBundle\Annotation\Worker;
--------------------------------------------------------------------------------
Thank you.

Sorry for my english basic. I am French.

**Comment by davidwdan** [comment]
Good catch.  I made those changes.
