### ISSUE TITLE
How to avoid wired response message show in backend?

### ISSUE THREAD

**Issue by cipherchien** [voryx/ThruwayBundle#13]
Hi, 

I try to develop a web chat system with ThruwayBundle, but I got a stuck situation.
When I try to publish message in backend, I got some wired response message.  
 
![screenruler-e824e513-0bd3-4ca5-846f-367f6568cc41](https://cloud.githubusercontent.com/assets/1157044/6820342/ebb3e5a4-d308-11e4-9506-09669c852f6e.png)

my backend code in Symfony:
```
$client = $this->container->get('thruway.client');
$client->publish("user.line.thread.55122ab298dee4fb020041b9", ['message sent from backend.']);  
```

My question is How to avoid that messages?

Thanks

By the way, I also check my config.yml setting.  I did disable logging display. 
voryx_thruway:
    realm: 'myrealm'
    enable_logging: false

**Comment by davidwdan** [comment]
Try adding this above your backend code: `Logger::set(new \Psr\Log\NullLogger());`.  

The `enable_logging` flag doesn't do anything right now.

**Comment by cipherchien** [comment]
Thank you so munc and reply so quickly.
here is my code, for someone who also need it.

```
use Thruway\Logging\Logger;

class UserChatController extends Controller
{ 
    .......
    public function doSendMessageAction(Request $request, $threadID)
    {
    .........
                //pusher
                Logger::set(new \Psr\Log\NullLogger());
                $this->get('thruway.client')->publish("user.line.thread.55122ab298dee4fb020041b9", 
                        array('coment.submit'), 
                        array(
                            'comment'=>$comment->getBody(),
                            'when'=>time()
                        ));
```
