### ISSUE TITLE
How to catch Connection.onclose event?

### ISSUE THREAD

**Issue by cipherchien** [voryx/ThruwayBundle#16]
Hi,

In AutobahnJS, I can use Connection.onclose this callback to catch the event.
Is it possible catch the same event with ThruwayBundle?

Thank you.

**Comment by cipherchien** [comment]
I found this:

https://github.com/voryx/Thruway/blob/master/Examples/SimpleClient.php
```
$onClose = function ($msg) {
    echo $msg;
};
$connection = new Connection(
    [
        "realm"   => 'realm1',
        "onClose" => $onClose,
        "url"     => 'ws://127.0.0.1:9090',
    ]
);
```

Is it possible have the config setting like this?


thank you.

**Comment by davidwdan** [comment]
You can listen to the close event on the `Client` like this:

```PHP
        $client = $this->get('voryx.thruway.client');
        $client->on('close', function($reason){

        });

```

**Comment by cipherchien** [comment]
It is not work..., I can't catch the event when user close his browser.
here is my code:  (I made a console command for testing) 
```
class OnCloseCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('oz:user:connection:onclose')
            ->setDescription("Do something when user lose connection." )
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $client = $this->getContainer()->get('voryx.thruway.client');
        
        $client->on('close', function($reason) use ($logger, $output) {
            $logger->info('I just close event');            
//            $logger->info($reason);          
            $output->writeln('got close event!');
        });        
    }
}
```

The result is it can't catch the event. I think the answer is:
The client with voryx.thruway.client and the client with thruway.client are independence.

May I have another solution? or just put it in my xmas wish list.

Thank you.

**Comment by mbonneau** [comment]
Closing this issue because it has been inactive for a while.
