### ISSUE TITLE
How to use the AuthorizationManager

### ISSUE THREAD

**Issue by stingus** [voryx/ThruwayBundle#30]
When starting the router with `thruway:router:start` or `thruway:process`, the default AutorizationManager is `AllPermissiveAuthorizationManager`. I want to: either use the default AuthorizationManager or build a custom one, since I have the exact same requirements as https://github.com/voryx/ThruwayBundle/pull/26 (not merged yet). Is there any better way to do this except creating a new command and setting an `AuthorizationManagerInterface` instance on the server (`voryx.thruway.server`)?
Can you please give me some guidance for the best approach on making this work?

**Comment by davidwdan** [comment]
@stingus I merged #26.  Let me know if need anything else.

**Comment by stingus** [comment]
Thanks @davidwdan, works like a charm.
