### ISSUE TITLE
This bundle is not yet compatible with Symfony3

### ISSUE THREAD

**Issue by fpasquet** [voryx/ThruwayBundle#32]
This problem comes from the librairy guzzle/guzzle.

**Comment by saidmoya12** [comment]
Same issue

**Comment by davidwdan** [comment]
I'm going to reopen this.   There are a couple of compatibility issues with Symfony3, which we're working on.

**Comment by davidwdan** [comment]
The main issue is with the scope prototype service option which was deprecated in 2.8 (replaced with `share`) and removed in 3.0.  If at all possible I want to keep backwards compatibility to 2.7.

**Comment by davidwdan** [comment]
@fpasquet and @saidmoya12 I just made some changes for this.  Can you test it out?  You'll still get the guzzle warning, but everything else should work.
