### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by fdydk** [voryx/ThruwayBundle#35]
can i find any examples for registering a topic ?

**Comment by stingus** [comment]
Do you mean subscribing to a topic (as in PUB/SUB)? Or registering a procedure (as in RPC)?

**Comment by fdydk** [comment]
how to register a topic as in pubsub

**Comment by davidwdan** [comment]
You can subscribe with the `Subscribe` annotation.  For more information see: https://github.com/voryx/ThruwayBundle#subscribe

**Comment by fdydk** [comment]
yes sure but i mean how to register the topic "the php class containing the subscribe  and publish method etc", what is the way to tell that this class is a topic

**Comment by davidwdan** [comment]
I guess I don't understand what you're asking.  You don't need to create a class to handle subscribe and publish.  You can just publish on or subscribe to a topic and the wamp router will handle everything else.

**Comment by fdydk** [comment]
u mean that i can add the subscribe and publish methods to a controller? i thought i have to create a service for that and register it somewhere

**Comment by davidwdan** [comment]
That's right, when you run the command `php app/console thruway:process start` it'll scan the AppBundle (or whatever bundle you specify in the config) for the annotations and wire everything up for you.

**Comment by fdydk** [comment]
and in the publish method what is com.myapp.hello_pubsub ?

    public function publish($value)
    {
        $client = $this->container->get('thruway.client');
        $client->publish("com.myapp.hello_pubsub", [$value]);
    }

**Comment by davidwdan** [comment]
`com.myapp.hello_pubsub` is the topic URI.  That can be whatever you want it to be as long as it's alphanumeric with period and underscores. Other clients can subscribe on that topic.

**Comment by fdydk** [comment]
ah so this is the same as in the annotation of the subscribe method, thanks a lot
