### ISSUE TITLE
Guzzle 3.9 compatibility issue with Symfony 3

### ISSUE THREAD

**Issue by mgiraud** [voryx/ThruwayBundle#37]
Guzzle 3.9 uses symfony/event-dispatcher ~2.1 which is not statisfiable by symfony 3.0.3

**Comment by davidwdan** [comment]
Guzzle 3.9 is a Ratchet dependency.  The [0.4](https://github.com/ratchetphp/Ratchet/tree/0.4) version of Ratchet removes that dependency, so when it's released, we'll be able to fix this.
