### ISSUE TITLE
Push message to specific user

### ISSUE THREAD

**Issue by NewOldMax** [voryx/ThruwayBundle#41]
Hi!

I'm trying to implement notifications in my project. My use case:
User 1 creates Task 1 and subscribes to "tasks" channel.
User 2 edits Task 1 and subscribes to "tasks" channel.
User 1 must receive notification about task edit, and User 2 should not receive this notification.

I see in docs:
````
$client = $this->container->get('thruway.client');
$client->publish("com.myapp.hello_pubsub", [$value]);
````
But as I understand, this code publishes message to all subscribed users.

Is there a way to push message for specific User, and not for all?

**Comment by davidwdan** [comment]
You can use the `_thruway_eligible_authids` option:

```PHP $client->publish("com.myapp.hello_pubsub", [$value], null, ["_thruway_eligible_authids"=>[$authid]]);```

You can also publish to specific roles with the `_thruway_eligible_authroles

**Comment by NewOldMax** [comment]
Hi, @davidwdan 

Thanks for answer. I tried your solution, but messages still published to all connected users, not for specific authid.

**Comment by NewOldMax** [comment]
My client setup (ReactJS)
````JavaScript
        AutobahnReact.Connection.makeConnection({
            url: 'ws://10.128.1.111:8080/ws',
            realm: 'realm1',
            authmethods: ["wampcra"],
            authid: localStorage.getItem('jwt'),
        });
        let connection = AutobahnReact.Connection.reconnectWithAuth(localStorage.getItem('jwt'), '');
        connection.then((session, details) => {
            console.log("Hey, connection established!");
            session[0].subscribe('app.tasks', (msg) => {
                console.log(msg);
            })
        }).catch((details) => {
          console.log("Hey, connection lost! " + details);
        })
````
And I tried
````PHP
        $client = $this->getContainer()->get('thruway.client');
        $authid = 'my_custom_jwt';
        $client->publish('app.tasks', ['test'], null, ['_thruway_eligible_authids' => [$authid]]);
````

**Comment by stingus** [comment]
Use a separate channel for each user, for example "com.myapp.hello_pubsub.12345", where 12345 is the user id. Don't forget to use the authorization manager to check the permissions to subscribe to individual channels. I have a similar notification system in place and it works really well.

**Comment by mbonneau** [comment]
I have tested the following using the WampCRA router in the Examples folder and found it to properly publish to only selected authids:
```php
<?php

use Thruway\Authentication\ClientWampCraAuthenticator;
use Thruway\ClientSession;
use Thruway\Peer\Client;
use Thruway\Transport\PawlTransportProvider;

require_once __DIR__ . '/vendor/autoload.php';

$client = new Client('realm1');

$client->addTransportProvider(new PawlTransportProvider('ws://127.0.0.1:9090/ws'));
$client->setAuthId('peter');
$client->addClientAuthenticator(new ClientWampCraAuthenticator('peter', 'secret1'));

$client->on('open', function (ClientSession $session) {
    $session->publish('some.topic', ['Hello everyone']);
    $session->publish(
        'some.topic',
        ['Joe should not see this'],
        null,
        ['_thruway_eligible_authids' => ['peter']]
    );
    $session->publish(
        'some.topic',
        ['This is for joe only'],
        null,
        ['_thruway_eligible_authids' => ['joe']]
    );
});

$client->start();
```
I then added this to WampCraLogin.html:
```javascript
session.subscribe('some.topic', function (args) {
    console.log(args);
});
```

Please note that this feature with be updated to match the current spec (`eligible_authid`) in the future. (we will deprecate the `_thruway_eligible_authids` for the next version prior to removable)

**Comment by NewOldMax** [comment]
It strange, but your example the same sends message to all users (not only for 'peter') :(

Can you share full code of your example? (i don't see WampCraLogin.html file)

**Comment by NewOldMax** [comment]
@stingus , in you solution, how you defined subscribe routes? I think i can't use something like
````PHP
   /**
     * @Subscribe("com.tasks.{userid}")
     */
````

**Comment by NewOldMax** [comment]
@davidwdan , @mbonneau , please, look at last update, if you have time.

**Comment by davidwdan** [comment]
@NewOldMax What version of Thruway are you using?

Adding a `-` to the regex will violate WAMP's strict URI conventions, which is what Thruway uses.

**Comment by NewOldMax** [comment]
I'm not specify version of Thruway, only install ThruwayBundle. In composer.lock Thruway version is 0.3.1

If there is a way to override regex for my use case? Or only use fork?

**Comment by davidwdan** [comment]
The ability to publish to specific users was added in [0.3.4](https://github.com/voryx/Thruway/releases/tag/0.3.4).  You should upgrade Thruway to at least that version.

**Comment by NewOldMax** [comment]
Successfully upgraded to 0.3.10 and all issues gone. You can close this issue now.
