### ISSUE TITLE
Exception AuthorizationManager is now a module

### ISSUE THREAD

**Issue by saidmoya12** [voryx/ThruwayBundle#48]
I', trying to use a custom AuthorizationManager but shown the message
AuthorizationManager is now a module.

How can use a custom authentication for actions?

Thanks

**Comment by davidwdan** [comment]
Can you post your router code?

**Comment by saidmoya12** [comment]
$router = new Router();				
	$userDb = new WampUser($this->getContainer()->get('fos_user.user_manager'));
	//$userDb->add('demo', '1234', 'salt123');
				
	$router->registerModule(new AuthenticationManager());
				
	$authProvClient = new WampCraAuthProvider(["realm1"]);
	$authProvClient->setUserDb($userDb);
	$router->addInternalClient($authProvClient);
				
	$router->registerModule(new RatchetTransportProvider("127.0.0.1", 9090));
				
	$router->start();

**Comment by davidwdan** [comment]
Make sure that your custom AuthenticationManager extends class extends RouterModuleClient and implements RealmModuleInterface.

If you're still having issues.  Feel free to reopen.
