### ISSUE TITLE
Support for Symfony3.x

### ISSUE THREAD

**Issue by jonescomas** [voryx/ThruwayBundle#49]
Please add support for Symfony3.x

**Comment by davidwdan** [comment]
What doesn't work with Symfony 3?

**Comment by pasblin** [comment]
hi ! composer.jon isny updated to symfony 3.x.
Regards

**Comment by tacman** [comment]
Can you replace this with the 2.6+ way?  It seems odd to support Symfony less than 2.6 but not support Symfony 3.

I'll make a PR

https://github.com/voryx/ThruwayBundle/blob/master/src/Voryx/ThruwayBundle/WampKernel.php#L488-L497


private function authenticateUser(UserInterface $user, ContainerInterface $container)
    {
        $providerKey = 'thruway';
        $token       = new UsernamePasswordToken($user, null, $providerKey, $user->getRoles());
        //Use the controller's container to set the token
        // This is deprecated in 2.6. we are leaving security.context for BC
        $container->get('security.context')->setToken($token);
        // This is what it should look like in 2.6+
        //$container->get('security.token_storage')->setToken($token);
    }

**Comment by mbonneau** [comment]
@tacman Did the PR that @davidwdan merge fix this issue?

**Comment by tacman** [comment]
Yep, thanks!

**Comment by mbonneau** [comment]
@jonescomas - is this issue resolved with #43 ?

**Comment by mike22** [comment]
@davidwdan Hi. How can I install this bundle for Symfony3? I wasn't able to get past composer requirements control.
My composer.json

`{
    "name": "fooProject",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "config": {
        "secure-http": false
    },
    "require": {
        "php": ">=7",
        "symfony/symfony": "3.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
	    "doctrine/mongodb": "dev-master",
        "doctrine/mongodb-odm": "dev-master",
        "doctrine/mongodb-odm-bundle": "dev-master",
        "alcaeus/mongo-php-adapter": "dev-master",
        "jms/serializer-bundle" : ">=0.1",
        "pear-pear.php.net/config_lite": "*",
        "facebook/php-sdk-v4" : "~5.0",
        "youshido/graphql-bundle": "^1.2",
        "voryx/thruway-bundle":"dev-master",
        "react/zmq":"@dev"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    },
    "repositories": [
      {
        "type": "pear",
        "url": "https://pear.php.net/"
      }
    ]
}`

Resulting in following error:
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/symfony v3.2.5
    - Conclusion: don't install symfony/symfony v3.2.4
    - Conclusion: don't install symfony/symfony v3.2.3
    - Conclusion: don't install symfony/symfony v3.2.2
    - Conclusion: don't install symfony/symfony v3.2.1
    - Conclusion: don't install symfony/symfony v3.2.0
    - Conclusion: remove symfony/symfony v3.1.10
    - Conclusion: don't install symfony/symfony v3.1.10
    - Conclusion: don't install symfony/symfony v3.1.9
    - Conclusion: don't install symfony/symfony v3.1.8
    - Conclusion: don't install symfony/symfony v3.1.7
    - Conclusion: don't install symfony/symfony v3.1.6
    - Conclusion: don't install symfony/symfony v3.1.5
    - Conclusion: don't install symfony/symfony v3.1.4
    - Conclusion: don't install symfony/symfony v3.1.3
    - Conclusion: don't install symfony/symfony v3.1.2
    - Conclusion: don't install symfony/symfony v3.1.1
    - Conclusion: don't install symfony/symfony v3.1.0
    - Conclusion: don't install symfony/symfony v3.0.9
    - Conclusion: don't install symfony/symfony v3.0.8
    - Conclusion: don't install symfony/symfony v3.0.7
    - Conclusion: don't install symfony/symfony v3.0.6
    - Conclusion: don't install symfony/symfony v3.0.5
    - Conclusion: don't install symfony/symfony v3.0.4
    - Conclusion: don't install symfony/symfony v3.0.3
    - Installation request for voryx/thruway-bundle dev-master -> satisfiable by voryx/thruway-bundle[dev-master].
    - Conclusion: don't install symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.1
    - voryx/thruway-bundle dev-master requires voryx/thruway ~0.4 -> satisfiable by voryx/thruway[0.4.0, 0.4.1, 0.4.2].
    - voryx/thruway 0.4.0 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - voryx/thruway 0.4.1 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - voryx/thruway 0.4.2 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - guzzle/guzzle v3.9.0 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.1 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.2 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - guzzle/guzzle v3.9.3 requires symfony/event-dispatcher ~2.1 -> satisfiable by symfony/event-dispatcher[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/event-dispatcher v2.5.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.5.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.13|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.6.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.13|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.14|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.15|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.16|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.17|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.18|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.19|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.20|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.21|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.22|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.23|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.24|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.25|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.7.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.13|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.14|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.15|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.16|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.17|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.18|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.8.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.13|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.1.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.2.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.11|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.12|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.13|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.14|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.15|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.16|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.17|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.18|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.19|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.20|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.21|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.22|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.23|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.24|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.25|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.26|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.27|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.28|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.29|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.30|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.31|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.32|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.33|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.34|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.35|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.36|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.37|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.38|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.39|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.40|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.41|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.42|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.3.9|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.0|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.1|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.10|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.2|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.3|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.4|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.5|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.6|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.7|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.8|don't install symfony/symfony v3.0.0
    - don't install symfony/event-dispatcher v2.4.9|don't install symfony/symfony v3.0.0
    - Installation request for symfony/symfony 3.* -> satisfiable by symfony/symfony[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5].
`

Thank you.

**Comment by mike22** [comment]
So it appears the solution is to add 
`        "symfony/event-dispatcher": "3.0.2 as 2.1"
`
to require field in composer.json

**Comment by BallisticPain** [comment]
@mike22 Thanks for sharing, but that's not a solution. It's a bandaid. Have we checked the version of Guzzle that supports the latest Symfony dispatcher? That's what will actually *fix* the issue. This isn't specifically a Thruway problem except it's requiring a version of Guzzle that relies on an old version of a Symfony component.

**Comment by stingus** [comment]
Try to require dev-master on voryx/thruway:
"voryx/thruway": "dev-master"
There's no dependency to guzzle/guzzle in the master.

**Comment by Gemorroj** [comment]
Better use `"voryx/thruway": "^0.5@dev"` instead `dev-master`.

**Comment by davidwdan** [comment]
@jonescomas Can you please test out dev-master with symfony 3?

**Comment by PhilETaylor** [comment]
I cant get this installed with Symfony 3 either :( 

> composer require "voryx/thruway":"^0.5@dev"

![screen shot 2017-12-30 at 20 48 56](https://user-images.githubusercontent.com/400092/34457242-dfe2f942-eda2-11e7-8649-396ef0f7c762.png)

**Comment by davidwdan** [comment]
@PhilETaylor can you try `dev-master`?

**Comment by davidwdan** [comment]
v0.3.0 supports SF3

**Comment by PhilETaylor** [comment]
Sorry for my delay - I forget the actual composer require command I used in the end but I had to pin a lot of the dependancies on older versions. 

my output (trimmed) of `composer show -i` is:
```
voryx/thruway                        0.5.1                         Thruway WAMP router core
voryx/thruway-common                 1.0.3                         WAMP2 Common Library for Thruway
thruway/client                       0.5.0                         Thruway WAMP client
thruway/pawl-transport               0.5.0                         Pawl WebSocket Transport for Thruway Client
thruway/ratchet-transport            0.5.0                         Ratchet Transport for Thruway
thruway/raw-socket-transport         0.5.0                         Raw Socket Transport for Thruway
evenement/evenement                  v2.1.0
```

and everything is working fine in Symfony v3.4.2

My biggest issue now will be migrating to Symfony 4 - but thats another major headache to come :)
