### ISSUE TITLE
How handle dynamic topic ?

### ISSUE THREAD

**Issue by ProPheT777** [voryx/ThruwayBundle#5]
Hi,

Simple question, how can I handle dynamic topic ? Simple use case, when you have a chat and you allow your client to create new room. Each room is a topic and when people enter in it, they subscribe to this room and publish. 

I'm blocked with this feature because of @Subscribe("chat/room1"), how handle chat/roomX ?

Currently I dont find a way to do that.

**Comment by mbonneau** [comment]
The latest commit (https://github.com/voryx/Thruway/commit/ba2166932c9e553980adf24e66e44f9cf3729f98) supports prefix matching.
