### ISSUE TITLE
JMS Serializer, API Platform and Thruway

### ISSUE THREAD

**Issue by tacman** [voryx/ThruwayBundle#50]
We're having issues running API Platform and Thruway together.  We've removed JMS Serializer from our project, and would prefer just to use Symfony's.

The problem is that Thruway installs JMS Serializer, which then uses the name 'Serializer'.

Is there a way to avoid this conflict?  We can fork it, but perhaps there's a way to set an alias or class of the Serializer?

**Comment by davidwdan** [comment]
@tacman We can look into that.  I would like to get rid of the dependency on JMS Serializer. 

Is the conflict with the `serializer` service?

**Comment by kcivey** [comment]
Yes, the problem is that the `serializer` service in this situation is the Symfony serializer, not JMS. Changing `id="serializer"` to `id="jms_serializer"` in services.xml in ThruwayBundle fixes it, so it would be good to have a configuration option for setting the serializer.

**Comment by mbonneau** [comment]
The lowest supported version of JMSSerializerBundle encourages the use of `jms_serializer` so it would be safe to make that quick change and then if desired it could be made configurable.

**Comment by kcivey** [comment]
Thanks!
