### ISSUE TITLE
Update Thruway server component to latest (0.5?)

### ISSUE THREAD

**Issue by tortoisedoc** [voryx/ThruwayBundle#69]
Current version of Thruway server in the bundle is 0.4. 

This version lacks Dealer role fix included last July 
https://github.com/voryx/Thruway/commit/2927b397dfaf4597be37786506cccb120ad814bb

Please update to latest version.

**Comment by tacman** [comment]
any updates on this?  We're prepping for the Symfony 3.4/4 release and trying to get all our libraries current.

**Comment by davidwdan** [comment]
@tacman and @tortoisedoc can you test the latest dev-master?

**Comment by tacman** [comment]
dev-master seems to be working fine for us.

**Comment by davidwdan** [comment]
v0.3.0 has been released with support for Thruway 0.5.0
