### ISSUE TITLE
Support for prefix matching

### ISSUE THREAD

**Issue by ThePixelDeveloper** [voryx/ThruwayBundle#78]
Currently there's no way of defining an annotation based subscription to support prefix matching. This code in the [WampKernel.php](https://github.com/voryx/ThruwayBundle/blob/master/src/Voryx/ThruwayBundle/WampKernel.php#L229-L238) doesn't support it. Can support be added for it? I have time to write a PR for it if that's of interest. 

It'll potentially help resolve the following problems as well: https://github.com/voryx/ThruwayBundle/issues/38 and https://github.com/voryx/ThruwayBundle/issues/5

**Comment by davidwdan** [comment]
A PR would be great!

**Comment by ThePixelDeveloper** [comment]
@davidwdan Submitted a PR. Would appreciate if you could take a look, thanks.
