### ISSUE TITLE
Does JMS serializer is not allowed ?

### ISSUE THREAD

**Issue by Hefarius** [voryx/ThruwayBundle#81]
Hello,

I have this error message after updating version : 
Type error: Argument 3 passed to Voryx\\ThruwayBundle\\Client\\ClientManager::__construct() must be an instance of Symfony\\Component\\Serializer\\Serializer, instance of JMS\\Serializer\\Serializer given

Can you have a solution for using JMS Serializer who allow group context and exclusion context ?
All of our application coree use JMS serializer, it is very complicated to change

Ty

Greg

**Comment by davidwdan** [comment]
If you want to use JMS serializer, you'll need to use version 0.2.0.  There might be a away to override the serializer in the current version, but I'm not 100%.

**Comment by stingus** [comment]
ThruwayBundle switched to Symfony serializer a while ago (https://github.com/voryx/ThruwayBundle/commit/a0de46f647bd0ea62651c247ef53d4abe152c337). If you were counting on serialization groups provided by JMS in the controller annotations, I think the only way is to do the serialization yourself with JMS and return the results. At least, that's what I did.

**Comment by arm1n** [comment]
It would be really great being able to make the choice about the used serializer on a per-project base. For my project it was impossible to stick to Symfony Serializer in conjunction with FOSRestBundle, but I like the approach [how serialization is handled in FOSRestBundle](http://symfony.com/doc/master/bundles/FOSRestBundle/1-setting_up_the_bundle.html#c-enable-a-serializer), so this would be a really great feature cause I think many people are still using and continue to use JMS serializer. If I would use serialization handled properly with Thruway I have to annotate all entities twice, i.e. for JMS and Symfony serializer, which doesn't feel DRY.

But yes, the workaround proposed by @stingus will also work, even though it runs the normalization process twice, which doesn't feel optimal neither. So what do you think?

BTW: Thanks for the great library, integration into Symfony worked seamlessly 👍

**Comment by Boimb** [comment]
Ho... I feel so ashamed :/
You just make me realized that we're running a so old version ...
Gonna fix some others conflicts that we didn't see before too 👍 
Great!
Cheers.
Boimb.

**Comment by Hefarius** [comment]
Thank you. The issue was solved.
Ticket can be closed.
