### ISSUE TITLE
How to get the client IP address in RPC call?

### ISSUE THREAD

**Issue by ThePixelDeveloper** [voryx/ThruwayBundle#83]
Looking to get the client IP address as part of an RPC call, but having trouble resolving what's the correct. Any help is much appreciated, I need it as an argument for the RPC.

**Comment by davidwdan** [comment]
Within the RPC, you can access the `thruway.details` service, which will provide a [Detail](https://github.com/voryx/ThruwayBundle/blob/master/src/Voryx/ThruwayBundle/Details.php) object with additional details.  

The ip address can be found in `$details->transport->transport_address`

**Comment by ThePixelDeveloper** [comment]
Managed to sort it out although it's not the most elegant solution. 

1. Had to override the `preProcessAuthenticate` in my custom authentication provider to pull out the `transport_address` and set it on the `extra` attribute.

    ``` php
    public function preProcessAuthenticate(array $args)
    {
        /**
         * @var HelloMessage $helloMsg
         */
        $helloMsg = HelloMessage::createMessageFromArray($args[0]->hello_message);
    
        $transport = $helloMsg->getDetails()->transport;
    
        $transportAddress = $transport->transport_address;
    
        $args = $args[0];
    
        $signature = $args->signature ?? null;
        $extra = $args->extra ?? null;
    
        if ($extra instanceof \stdClass) {
            $extra->transport_address = $transportAddress;
        }
    
        if (!$signature) {
            return ['ERROR'];
        }
    
        return $this->processAuthenticate($signature, $extra);
    }
    ```

2. Ensure my RPC implements ContainerAwareInterface. Inject the `thruway.container` using setter injection and then use the following code to pull out the value from the extra attributes.

    ``` php
    private function resolveIpAddress(): string
    {
        $container = $this->container;

        if ($container instanceof ContainerInterface) {
            if ($container->has('thruway.details') && $container->get('thruway.details') instanceof Details) {
                $details = $container->get('thruway.details')->getDetails();
                if (isset($details->_thruway_authextra) && $details->_thruway_authextra->transport_address) {
                    return $details->_thruway_authextra->transport_address;
                }
            }
        }

        return '';
    }
    ```

@davidwdan I assume you had something else in mind. I couldn't find the keys you described so had to do it the above way.

**Comment by ThePixelDeveloper** [comment]
Closing this as it's functionally resolved.
