### ISSUE TITLE
Doesn't work with symfony 3.4

### ISSUE THREAD

**Issue by flyer90** [voryx/ThruwayBundle#87]
After upgrading from symfony 3.3 to 3.4 I get his error: 
_The parameter \"container.build_id\" must be defined._

Followed the stack trace and identified where this happens: 
In **WampKernel.php**, function handleRPC, when it tries to **setControllerContainerUser**() it crashes when trying to get the repository.

Getting the repository results in calling this function
```   
 protected function getCache_AnnotationsService()
    {
        return $this->services['cache.annotations'] = new \Symfony\Component\Cache\Adapter\TraceableAdapter(\Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('fE1qHIkIjW', 0, $this->getParameter('container.build_id'), ($this->targetDirs[0].'/pools'), ${($_ = isset($this->services['monolog.logger.cache']) ? $this->services['monolog.logger.cache'] : $this->getMonolog_Logger_CacheService()) && false ?: '_'}));
    }
```
(in the appDevDebugProjectContainer.php)  and as you can see the function requires the **container.build_id parameter**, which is not set at this point

Can I fix this somehow?

Thank you

**Comment by davidwdan** [comment]
@mwsv did you upgrade to 3.4 or is this a new install?

**Comment by mwsv** [comment]
Thank you for your interest, it was update from 3.3 to 3.4 and ThruwayBundle was installed after that.

**Comment by davidwdan** [comment]
I'm not 100% sure, but I suspect it has something to do with the auto loader in your `app/console` or `bin/console` . 

Try replacing:
```PHP
require __DIR__.'/../app/autoload.php';
require_once __DIR__.'/AppKernel.php';
```

With:

```PHP
require __DIR__.'/../vendor/autoload.php';
```

**Comment by davidwdan** [comment]
We dug into this some more and were able to find this issue.  We'll have an update shortly.
