### ISSUE TITLE
Accessing the opened client's session from elsewhere

### ISSUE THREAD

**Issue by pdesmarais** [voryx/ThruwayBundle#9]
Hi!

I'm trying to figure out how to do this...

I'm using a Symfony Command to start my Thruway Router AND initializing my Client at the same time (pretty much like in [ThruwayClientCommand](https://github.com/voryx/ThruwayBundle/blob/master/src/Voryx/ThruwayBundle/Command/ThruwayClientCommand.php) except that my copy is using my `SocketClient` class which itself extends `Thruway\Peer\Client`).

Completely outside of the loop and not even within my browser, an event happens and calls a method of an ObjectManager class that I have. I need that ObjectManager's method to be able to publish to the socket that is already running from my cli Command.

How would I go about doing this? Am I not seeing it the right way? Should I be creating a new client just for this?

Thanks!

**Comment by davidwdan** [comment]
You're suppose to be able to just get the `thruway.client` service and publish on that.  That service will check to see if there is an existing open connection, and if not, it'll create one.  

```PHP
    $client = $this->container->get('thruway.client');
    $client->publish("com.myapp.helloPubSub", [$value]);
```

However, that appears to be broken right now, because I refactored the config and didn't update that part. 

I'll push up some changes in a little bit and add some instructions on how to configure it.

**Comment by pdesmarais** [comment]
Ok, cool! Thanks @davidwdan !

**Comment by pdesmarais** [comment]
@davidwdan I don't want to put any pressure by asking this. When you say "in a little bit", you mean sometime today or within the next few days of few weeks? ;)

Just want to manage my expectations. :)

Thanks again for your help!

**Comment by davidwdan** [comment]
I just pushed them up.

You'll need to add some settings to your config:

If you're using authentication, then you'll need to add a `trusted_port` to the router config and add a `trusted_uri` setting.

```YML
voryx_thruway:
    ...
    trusted_uri: 'ws://127.0.0.1:9991'
    router:
        ...
        trusted_port: '9991'
```
If you're not using authentication, you can just set the `trusted_uri` to your router's ip and port.

If you need to publish to the router from a php script (or any other language) that is not running within the same symfony project, you can use [WampPost](https://github.com/voryx/WampPost).

Let me know if you have any trouble getting any of this to work.

**Comment by pdesmarais** [comment]
Hey @davidwdan !

This works fine!

The only thing I see is that the client doesn't seem to be honoring the `enable_logging: false` that I have set in the config. I've seen the same thing when starting my `SocketServerCommand` but not always. Sometimes it just logs 
```
Making a go at starting the Thruway Client and Server running within a single process.
You can connect to this server on 'ws://127.0.0.1:8080' with the realm 'myrealm'
```

Do you have any idea what makes it behave like that? Should I create another issue for this?

Thanks!

**Comment by davidwdan** [comment]
Glad it's working.

Yeah, go ahead and open an issue for that.  It is something that needs to be addressed.  In the meantime, if you want to disable logging, you can add the follow line at the top of your `execute` method in your command or in any controller or service that you want to disable the logging for.

```PHP
Thruway\Logging\Logger::set(new \Psr\Log\NullLogger());
```

**Comment by pdesmarais** [comment]
Ok, cool.

I'll do that.

Thanks a lot!
