### ISSUE TITLE
Packagist verison 1.0.x-dev is not actual.

### ISSUE THREAD

**Issue by gam6itko** [voryx/ThruwayBundle#90]
Hello. Packagist contains old version 1.0.x-dev (2016-02-16 17:27 UTC). We recommend removing it.

**Comment by davidwdan** [comment]
Thanks.  It's been removed

**Comment by gam6itko** [comment]
It's still there.
https://packagist.org/packages/voryx/thruway-bundle#1.0.x-dev

**Comment by davidwdan** [comment]
That's strange, I definitely removed it.  I just did it again.
