### ISSUE TITLE
Use custom serializer to publish?

### ISSUE THREAD

**Issue by dark-matter-matters** [voryx/ThruwayBundle#97]
Hello, 
This bundle is pretty nice and is the only viable alternative to GOSWebSocketBundle. 

My problem is the default serializer. I have a ciruclar reference in one of my entities, and Symfony's default serializer is not able to avoid it and throws an exception : 

> A circular reference has been detected when serializing the object of class "Proxies\__CG__\App\Entity\User" (configured limit: 1)

The problem occurs on my listener when I try to send the response : 

```
private function publishInfo(LifecycleEventArgs $args)
{
        $entity = $args->getEntity();

        if ($entity instanceof User) {
            try {
                $this->thruway_client->publish("user.update", [$entity]);
            } catch (\Exception $e) {
                echo "Exception: " . $e->getMessage();
            }
        }
}
```

My API uses JMSSerializer, and it's able to solve circular dependencies. 
I saw on [your only tutorial](http://voryx.net/getting-started-with-the-thruwaybundle-for-symfony/) that you require this bundle, but I don't see where you ask Thruway to use it.

Thanks.

**Comment by valepu** [comment]
The tutorial is probably old. Thruwaybundle ditched JMS Serializer quite a few months ago. 
Looking on the internet i've noticed there are ways to handle circular references with symfony serializer. This is the first result i found on google: https://stackoverflow.com/questions/44286530/symfony-3-2-a-circular-reference-has-been-detected-configured-limit-1

**Comment by valepu** [comment]
In this issue: https://github.com/voryx/ThruwayBundle/issues/81 they discuss a workaround on how to use JMS serializer (serialize the object manually in your code and then publish the string, if i understood correctly)
